### ISSUE TITLE
Verification key for "armory-drive-log" not easily discoverable

### ISSUE THREAD

**Issue by mhutchinson** [f-secure-foundry/armory-drive-log#70]
The public key string for `armory-drive-log` should be discoverable so that checkpoints can be verified. Ideally this would be hosted on an external site with a link from here, though for now just popping it in a README would work.

Long term it would be best not to include it in the README as an attacker inside github could presumably then change both the checkpoint and the verification key.

**Comment by andrejro** [comment]
The log public key is stored in the [keys](https://github.com/f-secure-foundry/armory-drive-log/blob/master/key) directory.

The checkpoint signatures are performed by the [push_to_master](https://github.com/f-secure-foundry/armory-drive-log/blob/master/.github/workflows/push_to_master.yaml) action which has access to the log private key in its secrets envirionment. A github attacker wouldn't just use such private key instead of changing the public key?

**Comment by mhutchinson** [comment]
Wow, I totally didn't find those despite the obvious name of the directory. Mea culpa - thanks! You're also right about the threat model here. I'm not having a smart morning :-)

**Comment by abarisani** [comment]
The installer also highlights where keys are taken from:

```
$ ./armory-drive-install
...
Downloaded verified release assets
Downloading manifest authentication key from f-secure-foundry/armory-drive-log/keys/armory-drive.pub
Downloading transparency log authentication key from f-secure-foundry/armory-drive-log/keys/armory-drive-log.pub
...
```
